name: Daily Commit Workflow

on:
  schedule:
    - cron: '5 4 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commit with token - 24ds3000105@ds.study.iitm.ac.in
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "Daily commit at $(date)" >> daily-log.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit on $(date)" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin main
