name: Daily Commit Workflow

on:
  schedule:
    - cron: '5 4 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # ✅ Use PAT here directly

      - name: Add commit - 24ds3000105@ds.study.iitm.ac.in
        run: |
          echo "Daily commit at $(date)" >> daily-log.txt
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit on $(date)" || echo "Nothing to commit"
          git push
